spring:
  application:
    name: water-service
  data:
    mongodb:
      uri: "mongodb://localhost:27017/waterdb"
      database: "waterdb"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: "latest"
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    water: ingestion-water-events
    task-status: ingestion-status-events
    analytics: analytics-events
  consumer:
    group-id: water-group